import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
} from 'class-validator';

export class CreateItineraryDto {
  @IsUUID()
  @IsOptional() // usually generated by DB
  id?: string;

  @IsUUID()
  @IsOptional()
  userId?: string;

  @IsString()
  @MaxLength(255)
  @IsNotEmpty()
  title: string;

  @IsString()
  @IsOptional()
  description?: string;

  @IsString()
  @MaxLength(255)
  @IsOptional()
  destination?: string;

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  durationDays?: number;

  @IsOptional()
  canvasData?: Record<string, any>; // jsonb default {}

  @IsString()
  @IsOptional()
  thumbnailUrl?: string;

  @IsBoolean()
  @IsOptional()
  isPublic?: boolean;

  @IsBoolean()
  @IsOptional()
  isTemplate?: boolean;

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  price?: number;

  @IsString()
  @MaxLength(3)
  @IsOptional()
  currency?: string;

  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  tags?: string[];

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  viewCount?: number;

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  likeCount?: number;

  @IsString()
  @IsOptional()
  coverImageUrl?: string;

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  totalEstimatedCost?: number;

  @IsString()
  @MaxLength(20)
  @IsOptional()
  difficultyLevel?: string;

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  groupSizeMin?: number;

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  groupSizeMax?: number;

  @IsString()
  @MaxLength(50)
  @IsOptional()
  ageRestriction?: string;

  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  seasonBest?: string[];

  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  includes?: string[];

  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  excludes?: string[];

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  totalDays?: number;

  @IsString()
  @MaxLength(100)
  @IsOptional()
  createdBy?: string;

  @IsBoolean()
  @IsOptional()
  isFeatured?: boolean;

  @IsString()
  @MaxLength(100)
  @IsOptional()
  category?: string;

  @IsOptional()
  @IsNumber()
  travelers?: number;

  @IsOptional()
  @IsString()
  travelType: string;
}
